---
# tasks file for puppet
- name: Download do repositorio
  yum:
    name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
    state: present

- name: Instar o puppet e puppet lint
  yum: 
    name: puppet-agent 
    state: present
